# Generated by Django 4.2 on 2023-05-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_usertag_user_removed_usertagconnectiontable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile'),
        ),
    ]
