# Generated by Django 4.2 on 2023-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
