# Generated by Django 4.1.7 on 2023-03-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='portrait',
            new_name='image',
        ),
    ]
