# Generated by Django 4.2 on 2023-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_alter_comment_user_alter_page_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='free_access',
            new_name='access',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filepath',
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.FileField(default='file.*', upload_to='files'),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[['MUSIC', 'music'], ['VIDEO', 'video'], ['OTHER', 'other']], default='other'),
        ),
    ]
