# Generated by Django 4.2 on 2023-05-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0004_rename_free_access_page_access_remove_file_filepath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='access',
        ),
        migrations.AddField(
            model_name='file',
            name='comment_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='link_on',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_app.file')),
            ],
        ),
    ]
