# Generated by Django 4.2 on 2023-05-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0007_alter_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.AddField(
            model_name='file',
            name='public_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='page/default.jpg', upload_to='page'),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
