# Generated by Django 4.2 on 2023-05-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0008_remove_file_type_file_public_on_page_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='other'),
        ),
        migrations.AddField(
            model_name='page',
            name='comment_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='public_on',
            field=models.BooleanField(default=False),
        ),
    ]
